services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: python manage.py runserver 0.0.0.0:${PORT}
    volumes:
      - .:/code
    depends_on:
      - db
      - db-migrations
  db-migrations:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:14.12-alpine3.20
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - digiform_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  digiform_data:
    name: digiform_data