# Generated by Django 5.0.3 on 2024-06-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.UUIDField(primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('is_residence', models.BooleanField()),
                ('is_permenant', models.BooleanField()),
                ('is_mailing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.UUIDField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_legal_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('poc_1_name', models.CharField(max_length=100)),
                ('poc_1_mobile', models.BigIntegerField()),
                ('poc_1_email', models.EmailField(max_length=100)),
                ('poc_2_name', models.CharField(max_length=100)),
                ('poc_2_mobile', models.BigIntegerField()),
                ('poc_2_email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_forms_list', models.ManyToManyField(related_name='partner_forms_list', to='backend.form')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='form_partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_partner_id', to='backend.partner'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('marital_status', models.CharField(choices=[('UNMARRIED', 'Unmarried'), ('MARRIED', 'Married')], max_length=20)),
                ('dob', models.DateField()),
                ('mobile', models.BigIntegerField(db_index=True)),
                ('nationality', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('user_photo_link', models.URLField()),
                ('store_personal_data', models.BooleanField()),
                ('consent_for_digiform', models.BooleanField()),
                ('notifications_allowed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_address_id', to='backend.address')),
                ('mailing_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_address_id', to='backend.address')),
                ('permanent_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address_id', to='backend.address')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('personal_data_id', models.UUIDField(primary_key=True, serialize=False)),
                ('aadhar_card_number', models.BigIntegerField()),
                ('pan_card_number', models.CharField(default=None, max_length=10)),
                ('driving_license_number', models.CharField(default=None, max_length=20)),
                ('voter_id_number', models.CharField(default=None, max_length=20)),
                ('ration_card_number', models.CharField(default=None, max_length=20)),
                ('passport_number', models.CharField(default=None, max_length=20)),
                ('aadhaar_card_link', models.URLField()),
                ('pan_card_link', models.URLField()),
                ('driving_license_link', models.URLField()),
                ('voter_id_link', models.URLField()),
                ('ration_card_link', models.URLField()),
                ('passport_link', models.URLField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
    ]
