# Generated by Django 5.0.6 on 2024-07-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirm_details",
            field=models.BooleanField(null=True),
        ),
    ]
